version: '3.3'

services:
  # TODO webapp

  postgresql:
    container_name: "postgresql"
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../src/.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
