version: '3.3'

services:
  web:
    container_name: "fastapi-backend"
    build:
        context: .
        dockerfile: Dockerfile-FastAPI
    ports:
      - "8000:8000"
    env_file:
      - ../src/.env
    environment:
      "POSTGRES_HOST":"postgresql"
    command:
      - bash
      - -c
      - |
        while !</dev/tcp/postgresql/5432; do sleep 1; done;
        uvicorn main:app --host 0.0.0.0 --reload
    networks:
      - diploma
    depends_on:
      - postgresql

  postgresql:
    container_name: "postgresql"
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../src/.env
    ports:
      - "5432:5432"
    networks:
      - diploma
  
volumes:
  postgres_data:

networks:
  diploma:
    driver: bridge
