FROM python:3.9-slim-buster

WORKDIR /app
COPY src /app/
COPY requirements.txt /app/

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --default-timeout=100 -r requirements.txt

EXPOSE 8000
